version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    rust: "1.78"
  apt_packages:
    - gfortran
  jobs:
    pre_build:
      - git submodule update --init
      - cargo build
      - cd src/python/danton && ln -s ../../../target/debug/libdanton.so danton.so

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/source/requirements.txt
