name: AppImage
on:
  push:
    tags:
      - v*

jobs:
  AppImage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: |
        ./dist/appimage/build.sh
        echo "DANTON_APPIMAGE=danton-$(arch).AppImage" >> $GITHUB_ENV
        echo "DANTON_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Upload
      uses: AButler/upload-release-assets@v2.0
      with:
        files: ${{ env.DANTON_APPIMAGE }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ env.DANTON_VERSION }}
