name: Build
on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: |
        make

    - name: Examples
      run: |
        ./bin/danton examples/cards/grammage.json

  OSX:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: |
        make FC=gfortran-9

    - name: Examples
      run: |
        ./bin/danton examples/cards/grammage.json
